### ISSUE TITLE
HEIMDALL (0.3.0 n 0.3.2) unable to start up after downloading latest snapshot 

### ISSUE THREAD

**Issue by panbhatt** [maticnetwork/heimdall#960]
W are using HEIMDALL (o.3.2) to start up with the latest snapshot url ([
![image](https://user-images.githubusercontent.com/1473470/225709758-9abfe243-7285-4689-894f-c5c65ce2fa26.png)
](![image](https://user-images.githubusercontent.com/1473470/225709767-02b47372-bab1-4323-a600-48c3e3af6e70.png))

we have installed heimdall as per the instructions from [https://wiki.polygon.technology/docs/operate/full-node-binaries/](https://wiki.polygon.technology/docs/operate/full-node-binaries/)
Since starting from scratch is going to take very long time (read somewhere 9 days around, so we are using snapshot to get start quickly. 
we are working with the standard set of config files available in /var/lib/heimdall

The only change we had is we change the db_dir = "/custom/dir/data" which we get after unzipping the 202 GB file present over the link . 

we are getting two issues. 
1. when we start heimdall from the service we are seeing following issue. however our data directory is changed, so why this is even trying to get a lock over a file which we haven't specified. So service got killed after 4 attempt
![image](https://user-images.githubusercontent.com/1473470/225710540-8a6024fa-9a3f-4aaa-83cd-5ad66f8b3911.png)
2. When we are trying to start the server manually via the command "sudo /usr/bin/heimdalld start --home /var/lib/heimdall --chain=mainnet --rest-server" we are seeing following error & the rest server is not even starting up on port 26657, so we can't even chane the status. 
![image](https://user-images.githubusercontent.com/1473470/225711008-0e52573f-2329-4191-afae-b10fe38379b1.png)

3. we tried to start heimdall rest server separately, however it is listening on 1317 and /overview command is giving block height as zero. 

Does this mean HEIMDALL is still verifying the snapshot (and will wait to start the http server on port 26657 unless it is done).

**Comment by panbhatt** [comment]
the first issue is resolved. now we dont have any more LOCK situation. IT looks like the LOCK file is take over by ROOT while the process is started by the user "heimdall" so we resolved that. however Point no 2 is still going on, since last 6 hours

**Comment by Aracki** [comment]
I think 0.3.2 is not officially stable, as the image is still not pushed to https://hub.docker.com/r/0xpolygon/heimdall/tags
